Version "3.7"
services:
  web:
    container_name: nginx-jellyfin-web
    image: nginx
#    hostname: nginx-jellyfin-web
#    ports:
#      - "80:80"
#      - "443:443"
    volumes:
      - './www:/usr/share/nginx/html:ro'
    network: host
    restart: unless-stopped
